package example:calculator@0.1.0;

interface math {
    add: func(a: s32, b: s32) -> s32;
    multiply: func(a: s32, b: s32) -> s32;
}

interface console {
    print: func(line: string);
}

world calculator {
    import console;
    export math;
}